<?php
$thispage = 'pp-subscribe';
$pagetitle = 'Subscribe';
$pagedescription = 'Fetch plan details, get user to confirm details, collect shipping address, create billing agreement and redirect user to approval URL.';

/* approvalURL example =
https://www.sandbox.paypal.com/uk/cgi-bin/webscr?cmd=_flow&SESSION=-k37WXyfi2BCBmgJxjuAKGSK_xJRlm-4FmqHdDiIjBcdklh12akwayeshE4&dispatch=50a222a57771920b6a3d7b606239e4d529b525e0b7e69bf0224adecfb0124e9b61f737ba21b08198bdf3462ec1f5893fb648307135523787&rapidsState=OneX__CustomerBillingAgreementOneXFlow___StateOneXBA_Login&rapidsStateSignature=(null)
*/

require __DIR__ . '/includes/bootstrap.php';
use PayPal\Api\Agreement;
use PayPal\Api\Payer;
use PayPal\Api\Plan;
use PayPal\Api\ShippingAddress;

require __DIR__ . '/includes/countryCodes.php';

// if plan URL variable is set, fetch plan info
if(isset($_GET['plan'])) {

   // set template information
   switch ($_GET['plan']) {
      case 'plan1':
         $planID = 'P-123456'; // use plan id generated by UpdatePlan.php
         $agreementName = 'Plan One'; // name of agreement (different to plan name and can be individual to user)
         $agreementDescription = 'Plan Description'; // this is the description user sees when directed to PP
         break;
      case 'plan2':
         $planID = 'P-123456';
         $agreementName = 'Plan Two';
         $agreementDescription = 'Plan Description';
         break;
   }

   $_SESSION['planID'] = $planID; // save plan id to session to collect after agreemente executes

   // get plan info to show user
   try {
      $plan = Plan::get($planID, $apiContext);
   } catch (PayPalConnectionException $ex) {
      echo $ex->getCode();
      echo $ex->getData();
      die($ex);
   } catch (Exception $ex) {
      die($ex);
   }

   // convert json object to array and fetch plan details
   $result = json_decode($plan, true);
   if(isset($result['description'])) { $description = $result['description']; }
   if(isset($result['payment_definitions'][0]['frequency'])) { $paymentFrequency = $result['payment_definitions'][0]['frequency']; }
   if(isset($result['payment_definitions'][0]['amount']['currency'])) { $paymentCurrency = $result['payment_definitions'][0]['amount']['currency']; }
   if(isset($result['payment_definitions'][0]['amount']['value'])) { $paymentValue = $result['payment_definitions'][0]['amount']['value']; }

}

// process submitted form
if(isset($_POST['submit'])) {

   // check all fields are completed
   if(empty($_POST['address1'])) {
      $error[] = 'Please enter <strong>Address Line 1</strong>';
   }
   if(empty($_POST['city'])) {
      $error[] = 'Please enter a <strong>city</strong>';
   }
   if(empty($_POST['county'])) {
      $error[] = 'Please enter a <strong>County</strong>';
   }
   if(empty($_POST['postcode'])) {
      $error[] = 'Please enter a <strong>postcode</strong>';
   }
   if(empty($_POST['country'])) {
      $error[] = 'Please select a <strong>Country</strong>';
   }

   // if no errors set, create agreement
   if(!isset($error)) {

      $address1 = $_POST['address1'];
      $city = $_POST['city'];
      $county = $_POST['county'];
      $postcode = $_POST['postcode'];
      $country = $_POST['country'];

      $countrycode = array_search($country, $countrycodes_array); // find country code

      $datetime = new DateTime; // create current date
      //$datetime->add(new DateInterval('P1M')); // add one month
      $datetime->add(new DateInterval('PT30S')); // add 30 seconds
      $startdate = $datetime->format(DateTime::ATOM); // convert to ISO8601

      /* Create a new instance of Agreement object */
      $agreement = new Agreement();

      $agreement->setName($agreementName)
         ->setDescription($agreementDescription)
         ->setStartDate($startdate);

      $plan = new Plan();
      $plan->setId($planID);
      $agreement->setPlan($plan);

      // Add Payer
      $payer = new Payer();
      $payer->setPaymentMethod('paypal');
      $agreement->setPayer($payer);

      // Add Shipping Address
      $shippingAddress = new ShippingAddress();
      $shippingAddress->setLine1($address1)
         ->setCity($city)
         ->setState($county)
         ->setPostalCode($postcode)
         ->setCountryCode($countrycode);
      $agreement->setShippingAddress($shippingAddress);

      // ### Create Agreement
      try {
         $agreement = $agreement->create($apiContext);

         // ### Get redirect url
         $approvalUrl = $agreement->getApprovalLink();
      } catch (PayPalConnectionException $ex) {
         echo $ex->getCode();
         echo $ex->getData();
         die($ex);
      } catch (Exception $ex) {
         die($ex);
      }

      header('Location: '.$approvalUrl); // redirect user to generate approval url
      exit;
   }

}

require __DIR__ . '/includes/header.php';

   echo '
   <div class="container">
      <div class="row">';

         // if user has selected plan, display plan info to user
      if(isset($_GET['plan'])) {

         echo '
         <div class="col-xs-12 col-md-6">
            <h3>Agreement summary</h3>
            <p>
               <strong>Agreement name: </strong>'.$agreementName.'<br>
               <strong>Agreement description: </strong>'.$agreementDescription.'<br>
               <strong>Payment value: </strong>'.$paymentValue.'<br>
               <strong>Payment currency: </strong>'.$paymentCurrency.'<br>
               <strong>Payment frequency: </strong>'.$paymentFrequency.'<br>
               <strong>Session PlanID: </strong>'.$_SESSION['planID'].'<br>
            </p>
            <p>You will be charged this amount until you cancel the agreement. You can cancel at any time under your account. <br>
            <a href="#">See T&amp;Cs</a>.</p>
            <br>
         </div>

         <div class="col-xs-12 col-md-5 col-md-offset-1">
            <form id="confirm" name="confirm" method="post" action="">';

               if(isset($error)) {
                  echo '<div class="alert alert-danger center">';
                  foreach($error as $errors) {
                     echo '<p>'.$errors.'</p>';
                  }
                  echo '</div>';
               }

               echo '
               <div class="form-group">
                  <label for="address1">* Address Line 1:</label>
                  <input type="text" id="address1" name="address1" class="form-control" placeholder="Address Line 1"
                  value="'; if(isset($error)) { echo $_POST['address1']; } echo '" tabindex="1">
               </div>

               <div class="form-group">
                  <label for="city">* City:</label>
                  <input type="text" id="city" name="city" class="form-control" placeholder="City"
                  value="'; if(isset($error)) { echo $_POST['city']; } echo '" tabindex="2">
               </div>

               <div class="form-group">
                  <label for="county">* County/State:</label>
                  <input type="text" id="county" name="county" class="form-control" placeholder="County"
                  value="'; if(isset($error)) { echo $_POST['county']; } echo '" tabindex="3">
               </div>

               <div class="form-group">
                  <label for="postcode">* Postcode:</label>
                  <input type="text" id="postcode" name="postcode" class="form-control" placeholder="Postcode"
                  value="'; if(isset($error)) { echo $_POST['postcode']; } echo '" tabindex="4">
               </div>

               <div class="form-group">
                  <label for="country">* Country:</label>
                  <select id="country" name="country" class="form-control" tabindex="5">';
                     foreach ($countrycodes_array as $key => $value):
                        echo '<option value="'.$value.'"';
                        if(isset($error) && $_POST['country'] == $value) { echo ' selected'; }
                        elseif($value == 'UNITED KINGDOM') { echo ' selected'; }
                        echo '>'.$value.'</option>
                        ';
                     endforeach;
                  echo '
                  </select>
               </div>

               <div class="form-group">
                  <br>
                  <input type="submit" name="submit" value="Continue to PayPal" class="btn btn-default pull-right" tabindex="6">
               </div>

            </form>
         </div>';

      // if plan not selected, redirect user back to priceplans
      } else {

         echo '
         <div class="col-xs-12">
            <p>Plan not set, please <a href="priceplans.php">go back</a> and try again</p>
         </div>';

      }

      echo '
      </div>
   </div>';

   include __DIR__ . '/includes/footer.php';

?>
